#include "../src/sfs/ShaderIdentity.h"
#include <array>
#include <iostream>
int main(){
    // Results obtained by invoking the original isolated hash routine with
    // DllMain/import resolution disabled; fixtures are not generated by our code.
    const uint64_t expected[]={0x5bd27a2072b538,0x5141e65bca47a000,
        0x2bd9623ade670e44,0x196e5c0e3d1c34bf,0x5438d613f9e90d28,
        0x255652e1e467fb89,0x9cc8e798b4e43b90,0xc9ac7733dc21a4cc,
        0x1c9ed50d69bf4db2,0x614e5c9d7174c206,0x1adfb2f6da204ac2,
        0x6e479d4cae193103,0x4915a4cf1a05681e,0x4c81d39c6e918fd9,
        0xee98f169249e644c,0x9ebb166605890e10,0xa8253e521bf5c030};
    std::array<uint8_t,258> bytes{};
    for(size_t i=0;i<257;++i)bytes[i+1]=uint8_t(i*37+11);
    // Deliberately unaligned, including every possible tail length.
    for(uint32_t n=0;n<17;++n)if(kharvox::sfs::profileHash(bytes.data()+1,n)!=expected[n])return 1;
    for(auto item:{std::pair<uint32_t,uint64_t>{31,0xf8ce8a84cd914694},
                   {64,0x0d4e31a8ab2f6b6d},{257,0x67a9371d543adc4c}})
        if(kharvox::sfs::profileHash(bytes.data()+1,item.first)!=item.second)return 2;
    std::cout<<"20 original-binary hash vectors match\n";return 0;
}
