#pragma once
#include <vulkan/vulkan.h>
#include <stdexcept>
#include <string>

namespace kharvox::sfs {
// Resolve against this device's downstream dispatch once, before publishing State.
// Never use process-wide pointers: OpenXR may own another Vulkan device/layer chain.
struct NativeDispatch {
    PFN_vkCmdBeginQuery vkCmdBeginQuery{};
    PFN_vkCmdEndQuery vkCmdEndQuery{};
    PFN_vkCmdCopyBuffer vkCmdCopyBuffer{};
    PFN_vkCreateQueryPool vkCreateQueryPool{};
    PFN_vkDestroyQueryPool vkDestroyQueryPool{};
    PFN_vkResetQueryPool vkResetQueryPool{};
    PFN_vkResetQueryPoolEXT vkResetQueryPoolEXT{};
    PFN_vkCmdResetQueryPool vkCmdResetQueryPool{};
    PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp{};
    PFN_vkCmdWriteTimestamp2 vkCmdWriteTimestamp2{};
    PFN_vkCmdWriteTimestamp2KHR vkCmdWriteTimestamp2KHR{};
    PFN_vkGetQueryPoolResults vkGetQueryPoolResults{};
    PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults{};

    PFN_vkCreatePipelineLayout vkCreatePipelineLayout{};
    PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout{};
    PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers{};
    PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets{};
    PFN_vkAllocateMemory vkAllocateMemory{};
    PFN_vkBeginCommandBuffer vkBeginCommandBuffer{};
    PFN_vkCmdDrawIndexedIndirect vkCmdDrawIndexedIndirect{};
    PFN_vkCmdDrawIndirect vkCmdDrawIndirect{};
    PFN_vkCmdDrawIndexed vkCmdDrawIndexed{};
    PFN_vkCmdDraw vkCmdDraw{};
    PFN_vkCreateCommandPool vkCreateCommandPool{};
    PFN_vkEndCommandBuffer vkEndCommandBuffer{};
    PFN_vkBindBufferMemory vkBindBufferMemory{};
    PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass{};
    PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets{};
    PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer{};
    PFN_vkCmdBindPipeline vkCmdBindPipeline{};
    PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers{};
    PFN_vkCmdBlitImage vkCmdBlitImage{};
    PFN_vkCmdClearColorImage vkCmdClearColorImage{};
    PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage{};
    PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage{};
    PFN_vkCmdCopyImage vkCmdCopyImage{};
    PFN_vkCmdDispatch vkCmdDispatch{};
    PFN_vkCmdDispatchIndirect vkCmdDispatchIndirect{};
    PFN_vkCmdEndRenderPass vkCmdEndRenderPass{};
    PFN_vkCmdNextSubpass vkCmdNextSubpass{};
    PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier{};
    PFN_vkCmdPushConstants vkCmdPushConstants{};
    PFN_vkCmdResolveImage vkCmdResolveImage{};
    PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants{};
    PFN_vkCmdSetDepthBias vkCmdSetDepthBias{};
    PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds{};
    PFN_vkCmdSetLineWidth vkCmdSetLineWidth{};
    PFN_vkCmdSetScissor vkCmdSetScissor{};
    PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask{};
    PFN_vkCmdSetStencilReference vkCmdSetStencilReference{};
    PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask{};
    PFN_vkCmdSetViewport vkCmdSetViewport{};
    PFN_vkCreateBuffer vkCreateBuffer{};
    PFN_vkCreateComputePipelines vkCreateComputePipelines{};
    PFN_vkCreateDescriptorPool vkCreateDescriptorPool{};
    PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout{};
    PFN_vkCreateFramebuffer vkCreateFramebuffer{};
    PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines{};
    PFN_vkCreateImage vkCreateImage{};
    PFN_vkCreateImageView vkCreateImageView{};
    PFN_vkCreateRenderPass vkCreateRenderPass{};
    PFN_vkCreateShaderModule vkCreateShaderModule{};
    PFN_vkDestroyBuffer vkDestroyBuffer{};
    PFN_vkDestroyCommandPool vkDestroyCommandPool{};
    PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool{};
    PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout{};
    PFN_vkDestroyFramebuffer vkDestroyFramebuffer{};
    PFN_vkDestroyImage vkDestroyImage{};
    PFN_vkDestroyImageView vkDestroyImageView{};
    PFN_vkDestroyPipeline vkDestroyPipeline{};
    PFN_vkDestroyRenderPass vkDestroyRenderPass{};
    PFN_vkDestroyShaderModule vkDestroyShaderModule{};
    PFN_vkDeviceWaitIdle vkDeviceWaitIdle{};
    PFN_vkFreeCommandBuffers vkFreeCommandBuffers{};
    PFN_vkFreeDescriptorSets vkFreeDescriptorSets{};
    PFN_vkFreeMemory vkFreeMemory{};
    PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements{};
    PFN_vkMapMemory vkMapMemory{};
    PFN_vkResetDescriptorPool vkResetDescriptorPool{};
    PFN_vkUnmapMemory vkUnmapMemory{};
    PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets{};
    void load(VkDevice device, PFN_vkGetDeviceProcAddr resolver) {
        vkCmdBeginQuery=reinterpret_cast<PFN_vkCmdBeginQuery>(resolver(device,"vkCmdBeginQuery"));
        vkCmdEndQuery=reinterpret_cast<PFN_vkCmdEndQuery>(resolver(device,"vkCmdEndQuery"));
        vkCmdCopyBuffer=reinterpret_cast<PFN_vkCmdCopyBuffer>(resolver(device,"vkCmdCopyBuffer"));
        vkCreateQueryPool=reinterpret_cast<PFN_vkCreateQueryPool>(resolver(device,"vkCreateQueryPool"));
        vkDestroyQueryPool=reinterpret_cast<PFN_vkDestroyQueryPool>(resolver(device,"vkDestroyQueryPool"));
        vkResetQueryPool=reinterpret_cast<PFN_vkResetQueryPool>(resolver(device,"vkResetQueryPool"));
        vkResetQueryPoolEXT=reinterpret_cast<PFN_vkResetQueryPoolEXT>(resolver(device,"vkResetQueryPoolEXT"));
        vkCmdResetQueryPool=reinterpret_cast<PFN_vkCmdResetQueryPool>(resolver(device,"vkCmdResetQueryPool"));
        vkCmdWriteTimestamp=reinterpret_cast<PFN_vkCmdWriteTimestamp>(resolver(device,"vkCmdWriteTimestamp"));
        vkCmdWriteTimestamp2=reinterpret_cast<PFN_vkCmdWriteTimestamp2>(resolver(device,"vkCmdWriteTimestamp2"));
        vkCmdWriteTimestamp2KHR=reinterpret_cast<PFN_vkCmdWriteTimestamp2KHR>(resolver(device,"vkCmdWriteTimestamp2KHR"));
        vkGetQueryPoolResults=reinterpret_cast<PFN_vkGetQueryPoolResults>(resolver(device,"vkGetQueryPoolResults"));
        vkCmdCopyQueryPoolResults=reinterpret_cast<PFN_vkCmdCopyQueryPoolResults>(resolver(device,"vkCmdCopyQueryPoolResults"));

        vkAllocateCommandBuffers=reinterpret_cast<PFN_vkAllocateCommandBuffers>(resolver(device,"vkAllocateCommandBuffers"));
        vkAllocateDescriptorSets=reinterpret_cast<PFN_vkAllocateDescriptorSets>(resolver(device,"vkAllocateDescriptorSets"));
        vkAllocateMemory=reinterpret_cast<PFN_vkAllocateMemory>(resolver(device,"vkAllocateMemory"));
        vkBeginCommandBuffer=reinterpret_cast<PFN_vkBeginCommandBuffer>(resolver(device,"vkBeginCommandBuffer"));
        vkCmdDrawIndexedIndirect=reinterpret_cast<PFN_vkCmdDrawIndexedIndirect>(resolver(device,"vkCmdDrawIndexedIndirect"));
        vkCmdDrawIndirect=reinterpret_cast<PFN_vkCmdDrawIndirect>(resolver(device,"vkCmdDrawIndirect"));
        vkCmdDrawIndexed=reinterpret_cast<PFN_vkCmdDrawIndexed>(resolver(device,"vkCmdDrawIndexed"));
        vkCmdDraw=reinterpret_cast<PFN_vkCmdDraw>(resolver(device,"vkCmdDraw"));
        vkCreateCommandPool=reinterpret_cast<PFN_vkCreateCommandPool>(resolver(device,"vkCreateCommandPool"));
        vkEndCommandBuffer=reinterpret_cast<PFN_vkEndCommandBuffer>(resolver(device,"vkEndCommandBuffer"));
        vkBindBufferMemory=reinterpret_cast<PFN_vkBindBufferMemory>(resolver(device,"vkBindBufferMemory"));
        vkCmdBeginRenderPass=reinterpret_cast<PFN_vkCmdBeginRenderPass>(resolver(device,"vkCmdBeginRenderPass"));
        vkCmdBindDescriptorSets=reinterpret_cast<PFN_vkCmdBindDescriptorSets>(resolver(device,"vkCmdBindDescriptorSets"));
        vkCmdBindIndexBuffer=reinterpret_cast<PFN_vkCmdBindIndexBuffer>(resolver(device,"vkCmdBindIndexBuffer"));
        vkCmdBindPipeline=reinterpret_cast<PFN_vkCmdBindPipeline>(resolver(device,"vkCmdBindPipeline"));
        vkCmdBindVertexBuffers=reinterpret_cast<PFN_vkCmdBindVertexBuffers>(resolver(device,"vkCmdBindVertexBuffers"));
        vkCmdBlitImage=reinterpret_cast<PFN_vkCmdBlitImage>(resolver(device,"vkCmdBlitImage"));
        vkCmdClearColorImage=reinterpret_cast<PFN_vkCmdClearColorImage>(resolver(device,"vkCmdClearColorImage"));
        vkCmdClearDepthStencilImage=reinterpret_cast<PFN_vkCmdClearDepthStencilImage>(resolver(device,"vkCmdClearDepthStencilImage"));
        vkCmdCopyBufferToImage=reinterpret_cast<PFN_vkCmdCopyBufferToImage>(resolver(device,"vkCmdCopyBufferToImage"));
        vkCmdCopyImage=reinterpret_cast<PFN_vkCmdCopyImage>(resolver(device,"vkCmdCopyImage"));
        vkCmdDispatch=reinterpret_cast<PFN_vkCmdDispatch>(resolver(device,"vkCmdDispatch"));
        vkCmdDispatchIndirect=reinterpret_cast<PFN_vkCmdDispatchIndirect>(resolver(device,"vkCmdDispatchIndirect"));
        vkCmdEndRenderPass=reinterpret_cast<PFN_vkCmdEndRenderPass>(resolver(device,"vkCmdEndRenderPass"));
        vkCmdNextSubpass=reinterpret_cast<PFN_vkCmdNextSubpass>(resolver(device,"vkCmdNextSubpass"));
        vkCmdPipelineBarrier=reinterpret_cast<PFN_vkCmdPipelineBarrier>(resolver(device,"vkCmdPipelineBarrier"));
        vkCmdPushConstants=reinterpret_cast<PFN_vkCmdPushConstants>(resolver(device,"vkCmdPushConstants"));
        vkCmdResolveImage=reinterpret_cast<PFN_vkCmdResolveImage>(resolver(device,"vkCmdResolveImage"));
        vkCmdSetBlendConstants=reinterpret_cast<PFN_vkCmdSetBlendConstants>(resolver(device,"vkCmdSetBlendConstants"));
        vkCmdSetDepthBias=reinterpret_cast<PFN_vkCmdSetDepthBias>(resolver(device,"vkCmdSetDepthBias"));
        vkCmdSetDepthBounds=reinterpret_cast<PFN_vkCmdSetDepthBounds>(resolver(device,"vkCmdSetDepthBounds"));
        vkCmdSetLineWidth=reinterpret_cast<PFN_vkCmdSetLineWidth>(resolver(device,"vkCmdSetLineWidth"));
        vkCmdSetScissor=reinterpret_cast<PFN_vkCmdSetScissor>(resolver(device,"vkCmdSetScissor"));
        vkCmdSetStencilCompareMask=reinterpret_cast<PFN_vkCmdSetStencilCompareMask>(resolver(device,"vkCmdSetStencilCompareMask"));
        vkCmdSetStencilReference=reinterpret_cast<PFN_vkCmdSetStencilReference>(resolver(device,"vkCmdSetStencilReference"));
        vkCmdSetStencilWriteMask=reinterpret_cast<PFN_vkCmdSetStencilWriteMask>(resolver(device,"vkCmdSetStencilWriteMask"));
        vkCmdSetViewport=reinterpret_cast<PFN_vkCmdSetViewport>(resolver(device,"vkCmdSetViewport"));
        vkCreateBuffer=reinterpret_cast<PFN_vkCreateBuffer>(resolver(device,"vkCreateBuffer"));
        vkCreateComputePipelines=reinterpret_cast<PFN_vkCreateComputePipelines>(resolver(device,"vkCreateComputePipelines"));
        vkCreateDescriptorPool=reinterpret_cast<PFN_vkCreateDescriptorPool>(resolver(device,"vkCreateDescriptorPool"));
        vkCreateDescriptorSetLayout=reinterpret_cast<PFN_vkCreateDescriptorSetLayout>(resolver(device,"vkCreateDescriptorSetLayout"));
        vkCreateFramebuffer=reinterpret_cast<PFN_vkCreateFramebuffer>(resolver(device,"vkCreateFramebuffer"));
        vkCreateGraphicsPipelines=reinterpret_cast<PFN_vkCreateGraphicsPipelines>(resolver(device,"vkCreateGraphicsPipelines"));
        vkCreateImage=reinterpret_cast<PFN_vkCreateImage>(resolver(device,"vkCreateImage"));
        vkCreateImageView=reinterpret_cast<PFN_vkCreateImageView>(resolver(device,"vkCreateImageView"));
        vkCreateRenderPass=reinterpret_cast<PFN_vkCreateRenderPass>(resolver(device,"vkCreateRenderPass"));
        vkCreateShaderModule=reinterpret_cast<PFN_vkCreateShaderModule>(resolver(device,"vkCreateShaderModule"));
        vkDestroyBuffer=reinterpret_cast<PFN_vkDestroyBuffer>(resolver(device,"vkDestroyBuffer"));
        vkDestroyCommandPool=reinterpret_cast<PFN_vkDestroyCommandPool>(resolver(device,"vkDestroyCommandPool"));
        vkDestroyDescriptorPool=reinterpret_cast<PFN_vkDestroyDescriptorPool>(resolver(device,"vkDestroyDescriptorPool"));
        vkDestroyDescriptorSetLayout=reinterpret_cast<PFN_vkDestroyDescriptorSetLayout>(resolver(device,"vkDestroyDescriptorSetLayout"));
        vkDestroyFramebuffer=reinterpret_cast<PFN_vkDestroyFramebuffer>(resolver(device,"vkDestroyFramebuffer"));
        vkDestroyImage=reinterpret_cast<PFN_vkDestroyImage>(resolver(device,"vkDestroyImage"));
        vkDestroyImageView=reinterpret_cast<PFN_vkDestroyImageView>(resolver(device,"vkDestroyImageView"));
        vkDestroyPipeline=reinterpret_cast<PFN_vkDestroyPipeline>(resolver(device,"vkDestroyPipeline"));
        vkCreatePipelineLayout=reinterpret_cast<PFN_vkCreatePipelineLayout>(resolver(device,"vkCreatePipelineLayout"));
        vkDestroyPipelineLayout=reinterpret_cast<PFN_vkDestroyPipelineLayout>(resolver(device,"vkDestroyPipelineLayout"));
        vkDestroyRenderPass=reinterpret_cast<PFN_vkDestroyRenderPass>(resolver(device,"vkDestroyRenderPass"));
        vkDestroyShaderModule=reinterpret_cast<PFN_vkDestroyShaderModule>(resolver(device,"vkDestroyShaderModule"));
        vkDeviceWaitIdle=reinterpret_cast<PFN_vkDeviceWaitIdle>(resolver(device,"vkDeviceWaitIdle"));
        vkFreeCommandBuffers=reinterpret_cast<PFN_vkFreeCommandBuffers>(resolver(device,"vkFreeCommandBuffers"));
        vkFreeDescriptorSets=reinterpret_cast<PFN_vkFreeDescriptorSets>(resolver(device,"vkFreeDescriptorSets"));
        vkFreeMemory=reinterpret_cast<PFN_vkFreeMemory>(resolver(device,"vkFreeMemory"));
        vkGetBufferMemoryRequirements=reinterpret_cast<PFN_vkGetBufferMemoryRequirements>(resolver(device,"vkGetBufferMemoryRequirements"));
        vkMapMemory=reinterpret_cast<PFN_vkMapMemory>(resolver(device,"vkMapMemory"));
        vkResetDescriptorPool=reinterpret_cast<PFN_vkResetDescriptorPool>(resolver(device,"vkResetDescriptorPool"));
        vkUnmapMemory=reinterpret_cast<PFN_vkUnmapMemory>(resolver(device,"vkUnmapMemory"));
        vkUpdateDescriptorSets=reinterpret_cast<PFN_vkUpdateDescriptorSets>(resolver(device,"vkUpdateDescriptorSets"));
    }
    template<class T> static T require(T pointer, const char* name) {
        if(!pointer) throw std::runtime_error(std::string("Missing Vulkan entry ")+name);
        return pointer;
    }
};
}
